name: TIL-Review

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install golang
      - run: sudo add-apt-repository ppa:longsleep/golang-backports
      - run: apt update
      - run: apt install golang-go

      - name: Run go test
        run: go test ./...

