name: TIL-Review

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: use docker golang
      - run: go version

      - name: Run go test
        run: ./script/go_test.sh
  build-and-run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: ./script/production/build_image.sh
      
      - name: Run everydayReview application
        run: ./script/production/run_everyday_review.sh



