name: TIL-Review

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # delete system golang
      - run: sudo apt-get autoremove --purge golang
      
      # install golang
      - run: sudo add-apt-repository ppa:longsleep/golang-backports
      - run: sudo apt update
      - run: sudo apt install golang-go

      - run: go version

      - name: Run go test
        run: go test ./...

